# Short imperative setup cues per movement, keyed by the same slug the art uses.
# Rule: <= ~8 words, do-this-not-why. The rationale stays behind the Why toggle.
C = {
"half-kneeling-hip-flexor-overhead-reach":["Tuck the pelvis BEFORE you reach","Squeeze the down-side glute","Reach overhead, side-bend away","No arching the low back"],
"couch-stretch":["Rear foot up the wall","Front shin vertical","Tuck the pelvis, ribs down","Chest tall, don't lean forward"],
"prayer-lat-stretch-kneeling":["Forearms on a bench, palms together","Hips back over the heels","Let the chest sink toward the floor","Breathe into the armpits"],
"child-s-pose-wide-knee":["Knees wide, big toes together","Hips back to the heels","Reach the arms long","Exhale and sink lower"],
"child-s-pose-wide-knee-reach-far":["Knees wide, big toes together","Walk the hands as far as they go","Ribs melt toward the floor","Long slow exhales"],
"child-s-pose-box-breathing":["Knees wide, hips to heels","Arms long, forehead down","In 4, hold 4, out 4, hold 4","Five rounds"],
"puppy-pose":["Hips stay stacked over the knees","Walk the hands forward","Melt the chest, not the hips","Armpits toward the floor"],
"bench-sink-lat-t-spine":["Elbows on a bench, shoulder-width","Hips back over the heels","Let the chest sink through","Palms up on the second set"],
"heel-sit-reach-back":["Sit back on the heels, chest to thighs","Hand behind the head","Drive the elbow floor to ceiling","Hips stay glued to the heels"],
"cat-cow-extended-hold":["Hands under shoulders, knees under hips","Exhale, round from the tailbone","Inhale, open the chest","Hold the extended end 10s"],
"thread-the-needle":["From all fours, thread one arm under","Let the shoulder settle, don't force it","Opposite hand presses the floor","Keep the hips square"],
"adductor-rock-back":["One leg straight out to the side, foot flat","Hands under the shoulders","Rock the hips back toward the heel","Stop before the low back rounds"],
"frog-stretch":["Knees wide, shins in line with them","Ankles flexed, feet out","Rock the hips back slowly","Never bounce"],
"pigeon-pose":["Front shin across, back leg long","Square the hips forward","Stack, don't collapse, onto the front hip","Fold when it settles"],
"world-s-greatest-stretch":["Deep lunge, both hands inside the front foot","Drop the back-side elbow toward the floor","Rotate and reach the top arm up","Eyes follow the hand"],
"walking-spiderman-reach":["Step into a deep lunge","Hands inside the front foot","Reach one arm to the ceiling","Step through, alternate sides"],
"supine-90-90-exhale-breathing":["Feet on a wall or chair, hips and knees 90°","Low back FLAT to the floor","In 4 through the nose, out 8 through pursed lips","Pause 3s with the air fully out"],
"legs-up-the-wall":["Hips close to the wall, legs up","Arms wide, palms up","Let the low back settle","Slow nasal breathing"],
"supine-spinal-twist":["Knees together, drop to one side","Opposite shoulder stays down","Look away from the knees","Exhale into the twist"],
"supine-floor-angel":["Low back flat, ribs down","Arms slide floor-level to overhead","Keep the backs of the hands down","Stop where the ribs flare"],
"foam-roller-t-spine-extension":["Roller across the mid-back","Support the head, hips down","Extend over it, exhale at the bottom","Move to 3 levels"],
"foam-roller-thoracic-extension":["Roller across the mid-back","Support the head, hips down","Extend over it, exhale at the bottom","Move to 3 levels"],
"roller-extension-full-exhale":["Roller across the mid-back, hips down","Exhale FULLY at the bottom of each rep","Pause 2s with the air out","Three levels, five reps each"],
"peanut-extension-low-ribs-t8-t10":["Peanut on the muscle, never on the bone","Start at the lower ribs","5 small crunches to pin the segment","Reach the arms overhead, thumbs to the floor"],
"peanut-extension-mid-t6-t8":["Move the peanut up one segment","5 small crunches to pin it","Reach overhead, hold 5s","Extra breath on any level that feels blocked"],
"peanut-extension-upper-t4-t6":["Peanut between the shoulder blades","Hips stay DOWN","5 crunches, then reach overhead","Don't extend through the low back"],
"box-breathing":["Lie down, knees bent","In 4, hold 4, out 4, hold 4","Nose only","Shoulders stay quiet"],
"open-book-side-lying":["Side-lying, top knee 90° on a pillow","The knee does NOT move","Rotate the top arm and chest open","Exhale hard at end range"],
"open-book-pelvis-pinned":["Top knee pinned to the pillow — it does not move","Rotate the chest toward the floor behind","Exhale hard, then sink another inch","Pelvis square the whole time"],
"bretzel":["Side-lying, top knee pinned by the opposite hand","Reach back, grab the bottom ankle","Heel toward the glute","Rotate the chest to the ceiling"],
"side-lying-rib-expansion-breathing":["Side-lying, top arm overhead","Inhale into the TOP-side ribs only","Slow and quiet","Five breaths, then switch"],
"90-90-hip-switches":["Both knees at 90°, front and back","Switch slowly, no hands","2s pause at each end","Chest tall throughout"],
"90-90-hip-switch-hold":["Both knees 90°, shin box","Switch slowly, no hands","Hold the end position","Chest stays tall"],
"90-90-hip-transitions":["Shin box, knees at 90°","Transition slowly side to side","Control it, don't flop","Pause at each end"],
"90-90-pail-rail":["Hinge over the front leg to end range","Hold 30s","PAIL: press the shin DOWN, 60-70%, 10s","RAIL: try to lift the knee UP, 10s"],
"cervical-rotation":["Chin level, no tilting","Rotate until it stops, don't force","3s hold at end range","Shoulders stay still"],
"prone-i-y-t-w":["Face down, forehead resting","Thumbs up, lift the arms off the floor","Move through I, Y, T, W","Neck stays long"],
"prone-shoulder-extension":["Face down, hands behind the back","Lift the hands toward the ceiling","Shoulder blades pinch down","Keep the ribs on the floor"],
"standing-quad-pull-pelvic-tilt":["Grab the ankle, knee pointing down","TUCK the pelvis first","Knees stay together","Stand tall, don't lean forward"],
"standing-forward-fold-sway":["Feet hip-width, soft knees","Fold from the hips","Let the head hang heavy","Sway gently side to side"],
"deep-squat-hold-supported-if-needed":["Feet shoulder-width, toes slightly out","Sink to the bottom","Elbows inside the knees, press out","Hold a rack if the heels lift"],
"elevated-hamstring-stretch":["Heel on a bench, leg straight","Hinge from the HIP, back flat","Toes pulled toward you","Stop before the back rounds"],
"wall-calf-straight-knee":["Ball of the foot on the wall","Back knee LOCKED straight","Drive the hips forward","Heel stays down"],
"wall-calf-bent-knee":["Ball of the foot on the wall","Bend the knee — this one is soleus","Drive the knee over the toes","Heel stays down"],
"doorway-pec-90-elbow":["Forearm flat on the frame, elbow at shoulder height","Step through with the same-side foot","Rotate the chest away","Ribs down, no arching"],
"doorway-pec-135-elbow":["Hand HIGH on the frame, elbow above shoulder","Step through and rotate away","This one is the clavicular fibres","Ribs down"],
"doorway-pec-stretch-90-elbow":["Forearm on the frame, elbow at shoulder height","Step through, rotate the chest away","Sternal fibres — the bench-press half","Ribs stay down"],
"doorway-pec-stretch-135-elbow":["Hand high on the frame, elbow above shoulder","Step through and rotate away","Clavicular fibres — the incline half","Ribs stay down"],
"doorway-lat-shoulder-hang":["Grip the frame high, one hand","Sit the hips back and away","Let the shoulder open","Breathe into the armpit"],
"wall-bicep-stretch":["Hand on the wall behind you, thumb up","Arm straight, shoulder height","Rotate the chest away","Stop at a stretch, not a pinch"],
"overhead-tricep-stretch":["Elbow overhead, hand down the spine","Other hand pulls the elbow back","Ribs down","Don't arch to get lower"],
"cross-body-posterior-delt":["Arm straight across the chest","Pull above the elbow, not on the joint","Shoulder stays DOWN","Don't rotate the torso"],
"upper-trap-levator-scap":["Ear toward the shoulder","Opposite hand anchors the seat","Turn the nose 45° down for levator","Gentle — no cranking"],
"upper-trap-levator-scap-release":["Anchor the opposite hand under the seat","Ear to shoulder for upper trap","Nose down 45° for levator","Gentle pressure only"],
"forearm-flexor-stretch":["Arm straight, palm up","Fingers pulled back and down","Elbow stays locked","Both sides"],
"forearm-extensor-stretch":["Arm straight, palm down","Bend the wrist down, pull the knuckles under","Elbow stays locked","Both sides"],
"leg-swings-front-back":["Hold something for balance","Let the leg SWING, don't force height","Torso stays quiet","Range builds each rep"],
"leg-swings-lateral":["Hold something, swing across the body","Toes pointing forward the whole time","Relaxed leg","Build range gradually"],
"hip-cars":["Stand tall, brace the trunk","Biggest slow circle you own","Only the hip moves","Both directions"],
"shoulder-cars":["Arm straight, thumb leading","Slowest circle you can make","Ribs down, no arching","Reverse the direction"],
"standing-club-rotations":["Club across the shoulders, golf posture","Rotate progressively bigger","Exhale into each turn","Hips and chest, not the low back"],
"club-across-shoulders-rotations":["Club across the shoulders, address posture","Turn both ways, bigger each rep","Exhale into the turn","Stay in your posture"],
"ramped-swings-50-90":["Start at 50%, build to 90%","Full finish every swing","Breathe out through impact","Never max out cold"],
"left-handed-swings":["Swing from the opposite side","Half speed, full range","Restores side-to-side symmetry","Five is enough"],
}
